// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: file_meta.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace BlueBox.FileMeta.Grpc {
  /// <summary>
  /// CRUD operations on the File domain.
  /// </summary>
  public static partial class FileMeta
  {
    static readonly string __ServiceName = "blue_box.file_meta.grpc.FileMeta";

    static readonly grpc::Marshaller<global::BlueBox.FileMeta.Grpc.FileRequest> __Marshaller_blue_box_file_meta_grpc_FileRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BlueBox.FileMeta.Grpc.FileRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::BlueBox.FileMeta.Grpc.File> __Marshaller_blue_box_file_meta_grpc_File = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BlueBox.FileMeta.Grpc.File.Parser.ParseFrom);

    static readonly grpc::Method<global::BlueBox.FileMeta.Grpc.FileRequest, global::BlueBox.FileMeta.Grpc.File> __Method_GetFileRecord = new grpc::Method<global::BlueBox.FileMeta.Grpc.FileRequest, global::BlueBox.FileMeta.Grpc.File>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFileRecord",
        __Marshaller_blue_box_file_meta_grpc_FileRequest,
        __Marshaller_blue_box_file_meta_grpc_File);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::BlueBox.FileMeta.Grpc.FileMetaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FileMeta</summary>
    public abstract partial class FileMetaBase
    {
      /// <summary>
      /// Retrieve metadata about a file with a given ID.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::BlueBox.FileMeta.Grpc.File> GetFileRecord(global::BlueBox.FileMeta.Grpc.FileRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FileMeta</summary>
    public partial class FileMetaClient : grpc::ClientBase<FileMetaClient>
    {
      /// <summary>Creates a new client for FileMeta</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public FileMetaClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FileMeta that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public FileMetaClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected FileMetaClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected FileMetaClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Retrieve metadata about a file with a given ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::BlueBox.FileMeta.Grpc.File GetFileRecord(global::BlueBox.FileMeta.Grpc.FileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFileRecord(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve metadata about a file with a given ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::BlueBox.FileMeta.Grpc.File GetFileRecord(global::BlueBox.FileMeta.Grpc.FileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFileRecord, null, options, request);
      }
      /// <summary>
      /// Retrieve metadata about a file with a given ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::BlueBox.FileMeta.Grpc.File> GetFileRecordAsync(global::BlueBox.FileMeta.Grpc.FileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFileRecordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieve metadata about a file with a given ID.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::BlueBox.FileMeta.Grpc.File> GetFileRecordAsync(global::BlueBox.FileMeta.Grpc.FileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFileRecord, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override FileMetaClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FileMetaClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(FileMetaBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetFileRecord, serviceImpl.GetFileRecord).Build();
    }

  }
}
#endregion
